# Generated by Django 5.0.1 on 2025-11-09 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=500)),
                ('total_count', models.IntegerField(default=0)),
                ('avg_flowrate', models.FloatField(blank=True, null=True)),
                ('avg_pressure', models.FloatField(blank=True, null=True)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('min_flowrate', models.FloatField(blank=True, null=True)),
                ('max_flowrate', models.FloatField(blank=True, null=True)),
                ('min_pressure', models.FloatField(blank=True, null=True)),
                ('max_pressure', models.FloatField(blank=True, null=True)),
                ('min_temperature', models.FloatField(blank=True, null=True)),
                ('max_temperature', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(max_length=100)),
                ('flowrate', models.FloatField()),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='api.dataset')),
            ],
        ),
    ]
